# Generated by Django 5.0 on 2024-01-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_tag_alter_article_options_scope_article_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["-name"],
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterField(
            model_name="scope",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.article",
                verbose_name="Статья",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Основной"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.tag",
                verbose_name="Тег",
            ),
        ),
    ]
