# Generated by Django 5.0 on 2024-01-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_tag_options_alter_scope_article_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scope",
            options={
                "ordering": ["-is_main", "-tag"],
                "verbose_name": "Добавить тег",
                "verbose_name_plural": "Добавить теги",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(through="articles.Scope", to="articles.tag"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.article",
                verbose_name="Статья",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tag",
                verbose_name="Тег",
            ),
        ),
        migrations.AddConstraint(
            model_name="scope",
            constraint=models.UniqueConstraint(
                fields=("article", "tag"), name="unique_article_tag"
            ),
        ),
    ]
