# Generated by Django 5.0 on 2024-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="sensor",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterField(
            model_name="measurement",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
