# Generated by Django 5.0 on 2024-01-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0002_alter_measurement_options_alter_sensor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="sensor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="measurement.sensor",
            ),
        ),
    ]
